[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  
[[plugins]]
  package = "@netlify/plugin-functions-core"

[functions."gold-price-tracker"]
  schedule = "0 0,8 * * *"