[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"

[functions."gold-price-tracker"]
  schedule = "28 0 * * *"